### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/ide-backend#3]
- Steps to run locally
- Explain Directory structure.

**Comment by Logan1x** [comment]
@abhishek97 i want to work on this issue but i don't know to how to run it locally. what are this repo's components and directory structure. can you redirect me to some links.

**Comment by Logan1x** [comment]
Directory structure like this ? 
![image](https://user-images.githubusercontent.com/10944610/40616644-70a80dde-62a9-11e8-8a3e-c4bbb8f75e0e.png)

**Comment by abhishek97** [comment]
@Logan1x That is what we are aiming for here. We don't have any docs for this project yet. As for the db schema required, we only have a single relation

```sql
CREATE TABLE codezzz (
    id integer NOT NULL,
    language text NOT NULL,
    code text NOT NULL,
    custom_input text,
    file_name text,
    CONSTRAINT lenchk_code CHECK ((pg_column_size(code) < 50000)),
    CONSTRAINT lenchk_input CHECK ((pg_column_size(custom_input) < 2000000))
);

CREATE SEQUENCE codezzz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE ONLY codezzz ALTER COLUMN id SET DEFAULT nextval('codezzz_id_seq'::regclass);

ALTER TABLE ONLY codezzz
    ADD CONSTRAINT codezzz_pkey PRIMARY KEY (id);
```

**Comment by ananay** [comment]
Done!

https://github.com/coding-blocks/ide-backend/pull/6

**Comment by ananay** [comment]
@abhishek97 Is this for 50 or 70? I see 20 + 50 added.

**Comment by abhishek97** [comment]
@ananay 70.
